PaddingOracleWebApp/Controllers/HomeController.cs
using PaddingOracleWebApp.Helpers;
using System;
using System.Diagnostics;
using System.Net;
using System.Security.Cryptography;
using System.Web.Mvc;

namespace PaddingOracleWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Encrypt() {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Encrypt(string plainText) {
            ViewBag.PlainText = plainText;
            byte[] encryptedBytes = AESCrypto.AES_EncryptString(plainText);
            string encryptedHexString = CryptoHelper.ConvertByteArrayToHexString(encryptedBytes);
            ViewBag.EncryptedHexString = encryptedHexString;
            return View("Index");
        }

        public ActionResult Decrypt(string secret) {
            string plainText = "The Magic Words are Squeamish Ossifrage";
            string response = "";
            if (string.IsNullOrEmpty(secret)) {
                response = "No secret? Sorry, bad request!";
                ViewBag.DecryptedText = response;
                HttpContext.Response.StatusCode = 400;
                return View();
            }
            try
            {
                byte[] encryptedBytes = CryptoHelper.ConvertHexStringToByteArray(secret);
                response = AESCrypto.AES_DecryptToString(encryptedBytes);

                if (plainText.Equals(response, StringComparison.OrdinalIgnoreCase))
                {
                    //Valid padding and valid plain text
                    HttpContext.Response.StatusCode = 200;
                }
                else {
                    //Valid padding, but incorrect format")
                    HttpContext.Response.StatusCode = 404;
                }
            }
            catch (CryptographicException cex)
            {
                //Invalid padding (Exception message: "Padding is invalid and cannot be removed.")
                HttpContext.Response.StatusCode = 403;
                response = cex.Message;
            }
            ViewBag.DecryptedText = response;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

PaddingOracleWebApp/Controllers/SecureHomeController.cs
using PaddingOracleWebApp.Helpers;
using System;
using System.Security.Cryptography;
using System.Web.Mvc;

namespace PaddingOracleWebApp.Controllers
{
    public class SecureHomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Encrypt()
        {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Encrypt(string plainText)
        {
            ViewBag.PlainText = plainText;
            byte[] encryptedBytes = AESCrypto.AES_EncryptString(plainText);
            string encryptedHexString = CryptoHelper.ConvertByteArrayToHexString(encryptedBytes);

            ViewBag.EncryptedHexString = encryptedHexString + "&HMacToken=" + GenerateHMac(encryptedHexString);
            return View("Index");
        }
        public static string GenerateHMac(string cipherText)
        {
            string HMacToken = TamperProofQueryString.GetTamperProofToken(cipherText);
            return HMacToken;
        }

        public ActionResult Decrypt(string secret, string HMacToken)
        {
            string msg = string.Empty;
            bool isValidQueryString = TamperProofQueryString.ValidateQueryString(secret, HMacToken, out msg);
            if (isValidQueryString)
            {
                string plainText = "The Magic Words are Squeamish Ossifrage";
                string response = "";
                if (string.IsNullOrEmpty(secret))
                {
                    response = "No secret? Sorry, bad request!";
                    ViewBag.DecryptedText = response;
                    HttpContext.Response.StatusCode = 400;
                    return View();
                }
                try
                {
                    byte[] encryptedBytes = CryptoHelper.ConvertHexStringToByteArray(secret);
                    response = AESCrypto.AES_DecryptToString(encryptedBytes);

                    if (plainText.Equals(response, StringComparison.OrdinalIgnoreCase))
                    {
                        //Valid padding and valid plain text
                        HttpContext.Response.StatusCode = 200;
                    }
                    else
                    {
                        //Valid padding, but incorrect format")
                        HttpContext.Response.StatusCode = 404;
                    }
                }
                catch (CryptographicException cex)
                {
                    //Invalid padding (Exception message: "Padding is invalid and cannot be removed.")
                    HttpContext.Response.StatusCode = 403;
                    response = cex.Message;
                }
                ViewBag.DecryptedText = response;
                return View();
            }
            else
            {
                ViewBag.ErrorMessage = msg;
                return View("AccessDenied");
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

PaddingOracleWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PaddingOracleWebApp/Views/Home/Decrypt.cshtml
@{
    ViewBag.Title = "Decrypt";
}
<h2>Here is your decrypted secret:</h2>
<h3>@ViewBag.DecryptedText</h3>

PaddingOracleWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    string plainText = ViewBag.PlainText;
    string encryptedHexString = ViewBag.EncryptedHexString;
}

<div class="jumbotron">
    <h2>Padding Oracle</h2>
    <p class="lead">Guess what? This has nothing to do with "Oracle" database :D</p>
    @*<p>And by the way, <i>The Magic Words are Squeamish Ossifrage</i></p>*@
</div>

<div class="row">
        <div class="col-xs-8">
            <form role="form" class="form-inline" method="post" action="~/Home/encrypt">
                <div class="input-group input-group-lg">
                    <input type="text" class="form-control" name="plainText" value="@plainText" />
                    <div class="input-group-btn">
                        <button type="submit" class="btn">Encrypt</button>
                    </div><!-- /btn-group -->
                </div><!-- /input-group -->
            </form>
    </div><!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-xs-8">
    @if (!string.IsNullOrEmpty(encryptedHexString))
    {<br />
        <div class="form-group">
            <h4>Cipher Text:</h4>
            <textarea class="form-control" rows="2" id="comment">@encryptedHexString</textarea>
        </div>

        <p class="lead">
            <a href="~/Home/Decrypt?secret=@encryptedHexString">Click this link</a> to decrypt the cipher text
        </p>

    }
    </div>
</div>

PaddingOracleWebApp/Views/SecureHome/AccessDenied.cshtml
@{
    ViewBag.Title = "AccessDenied";
}
<h2>Access Denied.</h2>

<h4>@ViewBag.ErrorMessage</h4>

PaddingOracleWebApp/Views/SecureHome/Decrypt.cshtml
@{
    ViewBag.Title = "Secure Decrypt";
}
<h2>Here is your decrypted secret:</h2>
<h3>@ViewBag.DecryptedText</h3>

PaddingOracleWebApp/Views/SecureHome/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    string plainText = ViewBag.PlainText;
    string encryptedHexString = ViewBag.EncryptedHexString;
}

<div class="jumbotron">
    <h2>Padding Oracle</h2>
    <p class="lead">Guess what? This has nothing to do with "Oracle" database :D</p>
    @*<p>And by the way, <i>The Magic Words are Squeamish Ossifrage</i></p>*@
</div>

<div class="row">
    <div class="col-xs-8">
        <form role="form" class="form-inline" method="post" action="~/SecureHome/encrypt">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control" name="plainText" value="@plainText" />
                <div class="input-group-btn">
                    <button type="submit" class="btn">Encrypt</button>
                </div><!-- /btn-group -->
            </div><!-- /input-group -->
        </form>
    </div><!-- /.col-xs-12 -->
</div><!-- /.row -->
<div class="row">
    <div class="col-xs-8">
        @if (!string.IsNullOrEmpty(encryptedHexString))
        {<br />
        <div class="form-group">
            <h4>Cipher Text:</h4>
            <textarea class="form-control" rows="2" id="comment">@encryptedHexString</textarea>
        </div>

        <p class="lead">
            <a href="~/SecureHome/Decrypt?secret=@encryptedHexString">Click this link</a> to decrypt the cipher text
        </p>

        }
    </div>
</div>

PaddingOracleWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Padding Oracle Target", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Secure Home", "Index", "SecureHome")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>